### ISSUE TITLE
Primer::Beta::Blankslate with border: true argument does not let margins around component be controlled

### ISSUE THREAD

**Issue by heynan0** [primer/view_components#1906]
The parent should be able to control the spacing around the view component. However, with

```
<%= render(Primer::Beta::Blankslate.new(border: true, mb: 3, ...) %>
```

A wrapper div is added and the `mb-3` class name applies to what's inside the box, instead of adding margin outside the box. As a result, there's no way to add spacing to the outside. The workaround is having to wrap the component itself in yet another div and use the class.

![Screenshot 2023-03-29 at 7 27 53 PM](https://user-images.githubusercontent.com/58703271/228690515-b3c50d76-6809-47b0-8504-eaa2b3ad7878.png)

This problem does not occur with `Primer::BlankslateComponent` because it simply adds the `border` class name to the same div as the blankslate:

```
class="blankslate blankslate-spacious border"
```

**Comment by lesliecdubs** [comment]
👋🏻 @heynan0, thanks for reporting this! We're going to move it to the backlog since there's a viable workaround by wrapping the component in a `div`, but we recognize this is something that could probably be fixed in the future. 

Note to Primer maintainers: this would be nice to fix when we move this component to stable.
