### ISSUE TITLE
Missing border for `:neutral` scheme row in BorderBox component

### ISSUE THREAD

**Issue by gnfisher** [primer/view_components#1937]
👋 We are using the Box component in discussions for our categories index view. We are adding a new feature, sections, and sections appear in a row with a `:neutral` rather than `:default` scheme. When one of these rows is the first row, there are some visual mishaps where the black bottom border of the header becomes invisible:

<img width="700" alt="Screenshot 2023-04-06 at 11 44 29 AM" src="https://user-images.githubusercontent.com/4742306/230433661-71ce6622-0f3d-43f9-a00f-493e74371285.png">

It looks to be from this css:

<img width="228" alt="image" src="https://user-images.githubusercontent.com/4742306/230433962-d3aa0bd3-8c1e-4a41-9b8f-09b3a39421b4.png">

There are curved radiuses that are visible when the background is dark. I don't believe the curved radius here is desired? Or not if there is a header?

<img width="238" alt="Screenshot 2023-04-06 at 11 50 50 AM" src="https://user-images.githubusercontent.com/4742306/230433704-d02b15c1-d441-4e56-8d3b-61b57114e027.png">

And this somehow inches the element a pixel higher, so the grey hides the black border. I don't think this is necessary, either? But I may be missing something.

**Comment by lesliecdubs** [comment]
Thanks for reporting, this looks like a bug to us.

@simurai PVC maintainers said you've looked into similar bugs in the past; do you have any thoughts on a quick fix? If it's not something you have a good sense about how to fix within 15minutes or less, let us know and maybe Primer Design will want to look into prioritizing it. cc @tallys

**Comment by simurai** [comment]
The [Box styles](https://primer.style/css/components/box) that the `BorderBox` component uses has [lots of rounded corner bugs](https://github.com/github/primer/issues/499) and is quite brittle/unreliable by using the `:first-of-type` selector. And there are like [454 files](https://github.com/search?q=repo%3Agithub%2Fgithub+Box-row&type=code) that use `Box-row` and that is just custom markup without using ViewComponents. So any change to the `Box` styles has a high risk of introducing other regressions. 😩 

That said, we also have never really tried to fix them, but would require lots of testing, just because of the high usage count and maybe would warrant a "Batch" effort?

> We are using the Box component in discussions for our categories index view.

Would it be possible to use a utility class like `rounded-0` to remove the rounded corners? And maybe also `mt-0` to add the border back?

**Comment by gnfisher** [comment]
> Would it be possible to use a utility class like `rounded-0` to remove the rounded corners? And maybe also `mt-0` to add the border back? Or is there a URL to reproduce?

Yes, we've already solved for ourselves using the `hx` prefix css hack in [this pr](https://github.com/github/github/pull/268971/files).
