### ISSUE TITLE
Dialog overlay is too light in dark mode

### ISSUE THREAD

**Issue by strackoverflow** [primer/view_components#2082]
This isn't really a bug but something that has come up quite a bit with the global navigation rollout. Users expect the side panel overlays (which are built with `Primer::Alpha::Dialog`) to darken the page contents, but in dark mode, the overlay actually lightens the contents:

<img width="1493" alt="Screenshot of a Primer dialog open with a light colored overlay" src="https://github.com/primer/view_components/assets/431533/d5b5b8c9-44ac-4817-842d-cf5e0071b05d">

I think most people expect the overlay to be darker, like the one behind GitHub's command palette, for example:

<img width="1493" alt="Screenshot of the command palette with a darker overlay" src="https://github.com/primer/view_components/assets/431533/e685aac1-c50c-49a7-b10c-e72c75a87bfc">

I'm sure part of it is a matter of preference but I wanted to drop this issue here since we've been hearing this quite a bit both internally and from external users. If for some reason we don't want to change the overlay color, would it be possible to make the overlay color configurable on a per-dialog basis?

**Comment by mperrotti** [comment]
cc @langermank @lukasoppermann - this seems like something that can be addressed in Primitives.

**Comment by langermank** [comment]
We're about to start testing a new set of colors for all of Primer, and we refined the backdrop value a bit. Here's a comparison:

| before | after |
| -- | -- |
| <img width="793" alt="image" src="https://github.com/primer/view_components/assets/18661030/4ceb946b-2be3-4da7-960a-d77c24864393"> | <img width="721" alt="image" src="https://github.com/primer/view_components/assets/18661030/e2bfcd22-b734-4f1f-8acf-5fd2bc17900f"> |

It still gets a little lighter, but not as drastically. Would it make sense for it to be _darker_ in a dark theme? Generally things are opposite in light/dark (so it darkens in light mode and lightens in dark mode).

@lukasoppermann should we fix this now, or wait for it to be fixed in the test? In the legacy tokens, the component is using a non component token of `color-neutral-muted` so we can't change the value, we have to add a new token. Fixing it now would look like:

- Adding a new token to the old build with this value
- Updating the CSS for PVC to use the new-old value as a fallback for the new-new value 😅

**Comment by langermank** [comment]
This has been addressed behind our color feature flag, so I'm going to close it (it will hit GA someday).

<img width="784" alt="overlay sidebar open in dark mode" src="https://github.com/primer/view_components/assets/18661030/7b7b6394-d6cd-487a-a7a0-9a1a451ece02">
