### ISSUE TITLE
Create `MarkdownToolbarComponent`

### ISSUE THREAD

**Issue by manuelpuyol** [primer/view_components#436]
https://github.com/github/markdown-toolbar-element

**Comment by koddsson** [comment]
@primer/view-components-reviewers; Instead of creating a `MarkdownToolbar` component, what do you think about creating a `MarkdownEnabledTextArea`? It makes a lot more sense as a component and would include the `<markdown-toolbar>` and [`<file-attachment>`](https://github.com/primer/view_components/issues/438) components.

![image](https://user-images.githubusercontent.com/318208/119351873-e5b7a200-bc98-11eb-94c8-6fcb7e552110.png)

**Comment by manuelpuyol** [comment]
I think we can work our way up on that one!

We could have:

1. `MarkdownToolbar` which wraps `<markdown-toolbar>`
1. `FileAttachmentTextArea` which is a `<textarea>` + `<file-attachment>`
1. `CommentBox` which is the screenshot you shared (`TabNav` + `MarkdownToolbar` + `FileAttachmentTextArea`)

I like the idea of creating atomic components and then building something bigger with them

**Comment by gaknoll** [comment]
@manuelpuyol We should make sure this is captured in the [Primer backlog](https://github.com/github/primer/projects/1) for tracking and visibility! @vdepizzol has explored designs for how we could build a flexible [Action bar component ](https://github.com/github/primer/issues/84) that would handle some of the responsive issues we face today and be flexible enough to be use for the markdown toolbar as well as other similar use cases. 

It is also worth noting that Memex has also requested essentially a `MarkdownEnabledTextArea` ([#190](https://github.com/github/primer/issues/190)) for Primer React Components. 

cc @yaili @broccolini

**Comment by inkblotty** [comment]
Due to several conversations with @khiga8 , @koddsson , @JoseInTheArena and @manuelpuyol -- I've removed the "good first issue" label and un-assigned my (n00b) self for the following reasons:

- the markdown_toolbar_component.rb API will need some adjustments to work "the right way" for Primer (for example, there are Google Analytics tags hard-coded on buttons)
- whether we use the markdown_toolbar_component or the github_specific_markdown_toolbar_component or some combination of the two is TBD

I am closing the linked WIP PR.
